# Generated by Django 3.2.6 on 2021-08-28 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20210823_0745"),
    ]

    operations = [
        migrations.AlterField(
            model_name="column",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="columns",
                to="core.project",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="column",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="core.column",
            ),
        ),
        migrations.AlterField(
            model_name="task", name="position", field=models.FloatField(default=0.0),
        ),
    ]
